# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - x-todo-poc-app-tama-111

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://${{ secrets.ContainerRegistory_ServerName }}/
          username: ${{ secrets.ContainerRegistory_UserName }}
          password: ${{ secrets.ContainerRegistory_Password }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./app
          push: true
          tags: https://${{ secrets.ContainerRegistory_ServerName }}/${{ secrets.ContainerRegistory_UserName }}/webapp:${{ github.sha }}
          file: ./app/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F02D4B531E4A4DAEAAB498A8189BDC0E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_549DB4DD54FC4DF8A944DC84FE5496FD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_87A10F02A5104788AEF8497C66AA28C3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'x-todo-poc-app-tama-111'
          slot-name: 'Production'
          images: 'https://${{ secrets.ContainerRegistory_ServerName }}/${{ secrets.ContainerRegistory_UserName }}/webapp:${{ github.sha }}'
          